Added French translations to My Details #26
Oakland-University/translations pull request #27
Opened 2018-06-14 20:17 UTC by JoshBrudnak

2018-06-15 20:55 UTC, cousquer requested changes
Heya @JoshBrudnak 👋 
I've try to do my best in the review! 😉 
Nice done! @JoshBrudnak 💯

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +      lngStrs.setApply("Appliquez");
Postuler

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +      lngStrs.setClose("Fermez");
Fermer

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +      lngStrs.setApplyToGradHeader("Appliquez pour obtenir son diplôme?");
Postuler pour obtenir votre diplôme ?

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +          "Nos archives indiquent que vous êtes un senior et n'avez pas encore appliqué pour obtenir son diplôme. Si vous êtes prêt à le faire, sélectionnez appliquez.");
Nos archives indiquent que vous êtes senior et n'avez pas encore appliqué pour postulé votre diplôme. Si vous êtes prêt à le faire, sélectionnez /"Appliquer/".

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +          "Nos archives indiquent que ce etudiante êtes un senior et n'avez pas encore appliqué pour obtenir son diplôme.");
Nos archives indiquent que cet(te) étudiant(e) est senior et qu’il (elle) n’a pas encore postulé pour obtenir son diplôme.

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +      lngStrs.setApplyToGradHeader("Appliquez pour obtenir son diplôme?");
watch out there is a space before "?" and "!" in french... 😉

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +      lngStrs.setAppliedToGradHeader("Vous avez appliqué pour obtenir son diplôme.");
Vous avez postulé pour obtenir votre diplôme !

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +          "Nos archives indiquent que vous avez appliqué pour obtenir son diplôme. Vérifiez votre email pour plus d'informations.");
Nos archives indiquent que vous avez postulé pour obtenir votre diplôme. Vérifiez votre messagerie pour plus d'informations.

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +      lngStrs.setDisplay("Afficher votre informations personnelles.");
Consulter vos informations personnelles.

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +      lngStrs.setSomethingWrong("Voyez-vous quelque chose d'incorrect?");
Voyez-vous quelque chose d'incorrect ? (@JoshBrudnak the space before "?"...)

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +      lngStrs.setChangeInfo("Cliquez ici pour mettre à jour votre information");
Cliquez ici pour mettre à jour vos informations

2018-06-15 20:55 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +      lngStrs.setClassStanding("Classe Debout");
🤔 not "uprighth class", I need to figure out the context...
If this means "Class Status"
french could be -> "Status du cours"

2018-06-15 21:02 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +          "Nos archives indiquent que vous êtes un senior et n'avez pas encore appliqué pour obtenir son diplôme. Si vous êtes prêt à le faire, sélectionnez appliquez.");
🤔  does "a senior" means "license student"?

2018-06-15 21:24 UTC, JoshBrudnak commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +          "Nos archives indiquent que vous êtes un senior et n'avez pas encore appliqué pour obtenir son diplôme. Si vous êtes prêt à le faire, sélectionnez appliquez.");
No, it means the student is in his last year of undergraduate schooling. :mortar_board:

2018-06-15 21:35 UTC, JoshBrudnak commented
Thanks for the review @cousquer. :1st_place_medal:

2018-06-15 21:46 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +          "Nos archives indiquent que vous êtes un senior et n'avez pas encore appliqué pour obtenir son diplôme. Si vous êtes prêt à le faire, sélectionnez appliquez.");
Nos archives indiquent que vous êtes étudiant en dernière année d'études de premier cycle et n'avez pas encore postulé à votre diplôme. Si vous êtes prêt à le faire, sélectionnez /"Appliquer/".

2018-06-15 21:54 UTC, cousquer commented
You're welcome 😉 I've updated my review.

2018-06-18 18:15 UTC, JoshBrudnak commented
@cousquer I fixed the issues. Thanks :100:

2018-06-22 15:32 UTC, JoshBrudnak commented
@cousquer when you get a chance can you update your review? Thanks.

2018-06-22 18:18 UTC, cousquer requested changes
2 mispellings...

2018-06-22 18:18 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +          "Nos archives indiquent que vous avez postulé pour obtenir son diplôme. Vérifiez votre messagerie pour plus d'informations.");
Nos archives indiquent que vous avez postulé pour obtenir **votre** diplôme.

2018-06-22 18:18 UTC, cousquer commented on src/main/java/edu/oakland/translations/services/MyDetailsTranslationsService.java
> +          "Nos archives indiquent que ce etudiante a postulé pour obtenir son diplôme.");
Nos archives indiquent que **cet étudiant** a postulé pour obtenir son diplôme.

2018-06-25 09:46 UTC, cousquer approved these changes

2018-06-25 14:05 UTC, merged